version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tOxaMBlETeNi
      MYSQL_ROOT_HOST: "%"

  bot:
    build:
      context: .
      dockerfile: DockerfileBot
    links:
      - db
    ports:
      - "5001:5001"